name = "gruvbox-dark-5"

[[stops]]
position = 0.0
r = 0.114
g = 0.125
b = 0.129

[[stops]]
position = 0.25
r = 0.224
g = 0.180
b = 0.118

[[stops]]
position = 0.5
r = 0.459
g = 0.196
b = 0.078

[[stops]]
position = 0.75
r = 0.682
g = 0.455
b = 0.169

[[stops]]
position = 1.0
r = 0.878
g = 0.776
b = 0.569
