name = "nord-5"

[[stops]]
position = 0.0
r = 0.180
g = 0.204
b = 0.251

[[stops]]
position = 0.25
r = 0.369
g = 0.424
b = 0.502

[[stops]]
position = 0.5
r = 0.698
g = 0.667
b = 0.749

[[stops]]
position = 0.75
r = 0.878
g = 0.808
b = 0.859

[[stops]]
position = 1.0
r = 0.925
g = 0.910
b = 0.925
