name = "tokyo-night-5"

[[stops]]
position = 0.0
r = 0.102
g = 0.110
b = 0.180

[[stops]]
position = 0.25
r = 0.247
g = 0.286
b = 0.490

[[stops]]
position = 0.5
r = 0.545
g = 0.553
b = 0.753

[[stops]]
position = 0.75
r = 0.816
g = 0.733
b = 0.851

[[stops]]
position = 1.0
r = 0.757
g = 0.875
b = 0.980
